/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.10.2/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit test framework.
    testImplementation(libs.junit)

    // This dependency is used by the application.
    implementation(libs.guava)

    implementation("io.javalin:javalin:5.0.1") // servidor http
    implementation("org.slf4j:slf4j-simple:2.0.9") // logger
    implementation("com.google.code.gson:gson:2.11.0") // json mapper
    implementation("com.auth0:java-jwt:4.4.0") // jwt util
    implementation("org.postgresql:postgresql:42.6.0") // jpdc postgres
    implementation("org.mindrot:jbcrypt:0.4") // password hash
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

application {
    // Define the main class for the application.
    mainClass = "org.example.App"
}
